apiVersion: v1
kind: Service
metadata:
  name: svc-openldap
spec:
  type: ClusterIP
  ports:
    - name: ldap
      protocol: TCP
      port: 389
      targetPort: 389
    - name: ldaps
      protocol: TCP
      port: 636
      targetPort: 636
  selector:
    app: openldap
